
-- LSST Database Metadata
-- $Revision$
-- $Date$
--
-- See <http://dev.lsstcorp.org/trac/wiki/Copyrights>
-- for copyright information.


--  ! ! !    W A R N I N G    ! ! !
-- do NOT update this file by hand. It is auto-generated by the
-- script cat/bin/schema_to_metadata.sql based on the schema 
-- description tables from schema file located in cat/sql/

DROP DATABASE IF EXISTS lsst_schema_browser_DC3a;
CREATE DATABASE lsst_schema_browser_DC3a;
USE lsst_schema_browser_DC3a;


CREATE TABLE md_Table (
	tableId INTEGER NOT NULL PRIMARY KEY,
	name VARCHAR(255) NOT NULL UNIQUE,
	engine VARCHAR(255),
	description TEXT
);

CREATE TABLE md_Column (
	columnId INTEGER NOT NULL PRIMARY KEY,
	tableId INTEGER NOT NULL REFERENCES md_Table (tableId),
	name VARCHAR(255) NOT NULL,
	description TEXT,
	type VARCHAR(255),
	notNull INTEGER DEFAULT 0,
	defaultValue VARCHAR(255),
	unit VARCHAR(255),
	ucd VARCHAR(255),
        displayOrder INTEGER NOT NULL,
	INDEX md_Column_idx (tableId, name)
);

CREATE TABLE md_Index (
	indexId INTEGER NOT NULL PRIMARY KEY,
	tableId INTEGER NOT NULL REFERENCES md_Table (tableId),
	type VARCHAR(64) NOT NULL,
	columns VARCHAR(255) NOT NULL,
	INDEX md_Column_idx (tableId)
) ;

CREATE TABLE md_DbDescr (
	schemaFile VARCHAR(255),
	revision VARCHAR(64)
);

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_DbDescr
SET schemaFile = "lsstSchema4mysqlDC3a.sql", revision = "4.7.1.0-16-g0ea6a9b";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 1, name = "AAA_Version_3_0_24";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 2, name = "CCD_Detector";

	INSERT INTO md_Column
	SET columnId = 1, tableId = 2, name = "ccdDetectorId",
		type = "INTEGER",
		notNull = 1,
		defaultValue = "1",
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 2, tableId = 2, name = "biasSec",
		type = "VARCHAR(20)",
		notNull = 1,
		defaultValue = "'[0:0,0:0]'",
		displayOrder = 2;

	INSERT INTO md_Column
	SET columnId = 3, tableId = 2, name = "trimSec",
		type = "VARCHAR(20)",
		notNull = 1,
		defaultValue = "'[0:0,0:0]'",
		displayOrder = 3;

	INSERT INTO md_Column
	SET columnId = 4, tableId = 2, name = "gain",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 4;

	INSERT INTO md_Column
	SET columnId = 5, tableId = 2, name = "rdNoise",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 5;

	INSERT INTO md_Column
	SET columnId = 6, tableId = 2, name = "saturate",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 6;

	INSERT INTO md_Index
	SET indexId = 1, tableId = 2,
		type = "PRIMARY KEY",
		columns = "ccdDetectorId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 3, name = "DIASource",
	engine = "MyISAM";

	INSERT INTO md_Column
	SET columnId = 7, tableId = 3, name = "diaSourceId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 8, tableId = 3, name = "ampExposureId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Column
	SET columnId = 9, tableId = 3, name = "diaSourceToId",
		type = "BIGINT",
		notNull = 0,
		displayOrder = 3;

	INSERT INTO md_Column
	SET columnId = 10, tableId = 3, name = "filterId",
		type = "TINYINT",
		notNull = 1,
		displayOrder = 4;

	INSERT INTO md_Column
	SET columnId = 11, tableId = 3, name = "objectId",
		type = "BIGINT",
		notNull = 0,
		displayOrder = 5;

	INSERT INTO md_Column
	SET columnId = 12, tableId = 3, name = "movingObjectId",
		type = "BIGINT",
		notNull = 0,
		displayOrder = 6;

	INSERT INTO md_Column
	SET columnId = 13, tableId = 3, name = "xAstrom",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 7;

	INSERT INTO md_Column
	SET columnId = 14, tableId = 3, name = "xAstromErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 8;

	INSERT INTO md_Column
	SET columnId = 15, tableId = 3, name = "yAstrom",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 9;

	INSERT INTO md_Column
	SET columnId = 16, tableId = 3, name = "yAstromErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 10;

	INSERT INTO md_Column
	SET columnId = 17, tableId = 3, name = "ra",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 11;

	INSERT INTO md_Column
	SET columnId = 18, tableId = 3, name = "raErrForDetection",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 12;

	INSERT INTO md_Column
	SET columnId = 19, tableId = 3, name = "raErrForWcs",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 13;

	INSERT INTO md_Column
	SET columnId = 20, tableId = 3, name = "decl",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 14;

	INSERT INTO md_Column
	SET columnId = 21, tableId = 3, name = "declErrForDetection",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 15;

	INSERT INTO md_Column
	SET columnId = 22, tableId = 3, name = "declErrForWcs",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 16;

	INSERT INTO md_Column
	SET columnId = 23, tableId = 3, name = "taiMidPoint",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 17;

	INSERT INTO md_Column
	SET columnId = 24, tableId = 3, name = "taiRange",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 18;

	INSERT INTO md_Column
	SET columnId = 25, tableId = 3, name = "Ixx",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 19;

	INSERT INTO md_Column
	SET columnId = 26, tableId = 3, name = "IxxErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 20;

	INSERT INTO md_Column
	SET columnId = 27, tableId = 3, name = "Iyy",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 21;

	INSERT INTO md_Column
	SET columnId = 28, tableId = 3, name = "IyyErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 22;

	INSERT INTO md_Column
	SET columnId = 29, tableId = 3, name = "Ixy",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 23;

	INSERT INTO md_Column
	SET columnId = 30, tableId = 3, name = "IxyErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 24;

	INSERT INTO md_Column
	SET columnId = 31, tableId = 3, name = "psfFlux",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 25;

	INSERT INTO md_Column
	SET columnId = 32, tableId = 3, name = "psfFluxErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 26;

	INSERT INTO md_Column
	SET columnId = 33, tableId = 3, name = "apFlux",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 27;

	INSERT INTO md_Column
	SET columnId = 34, tableId = 3, name = "apFluxErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 28;

	INSERT INTO md_Column
	SET columnId = 35, tableId = 3, name = "modelFlux",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 29;

	INSERT INTO md_Column
	SET columnId = 36, tableId = 3, name = "modelFluxErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 30;

	INSERT INTO md_Column
	SET columnId = 37, tableId = 3, name = "instFlux",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 31;

	INSERT INTO md_Column
	SET columnId = 38, tableId = 3, name = "instFluxErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 32;

	INSERT INTO md_Column
	SET columnId = 39, tableId = 3, name = "apDia",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 33;

	INSERT INTO md_Column
	SET columnId = 40, tableId = 3, name = "flagForClassification",
		type = "BIGINT",
		notNull = 0,
		displayOrder = 34;

	INSERT INTO md_Column
	SET columnId = 41, tableId = 3, name = "flagForDetection",
		type = "BIGINT",
		notNull = 0,
		displayOrder = 35;

	INSERT INTO md_Column
	SET columnId = 42, tableId = 3, name = "snr",
		type = "FLOAT",
		notNull = 1,
		displayOrder = 36;

	INSERT INTO md_Column
	SET columnId = 43, tableId = 3, name = "chi2",
		type = "FLOAT",
		notNull = 1,
		displayOrder = 37;

	INSERT INTO md_Index
	SET indexId = 2, tableId = 3,
		type = "PRIMARY KEY",
		columns = "diaSourceId";

	INSERT INTO md_Index
	SET indexId = 3, tableId = 3,
		type = "UNIQUE",
		columns = "diaSourceToId";

	INSERT INTO md_Index
	SET indexId = 4, tableId = 3,
		type = "-",
		columns = "movingObjectId";

	INSERT INTO md_Index
	SET indexId = 5, tableId = 3,
		type = "-",
		columns = "ampExposureId";

	INSERT INTO md_Index
	SET indexId = 6, tableId = 3,
		type = "-",
		columns = "filterId";

	INSERT INTO md_Index
	SET indexId = 7, tableId = 3,
		type = "-",
		columns = "movingObjectId";

	INSERT INTO md_Index
	SET indexId = 8, tableId = 3,
		type = "-",
		columns = "objectId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 4, name = "Filter";

	INSERT INTO md_Column
	SET columnId = 44, tableId = 4, name = "filterId",
		type = "INTEGER",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 45, tableId = 4, name = "filtURL",
		type = "VARCHAR(255)",
		notNull = 0,
		displayOrder = 2;

	INSERT INTO md_Column
	SET columnId = 46, tableId = 4, name = "filtName",
		type = "VARCHAR(255)",
		notNull = 1,
		displayOrder = 3;

	INSERT INTO md_Column
	SET columnId = 47, tableId = 4, name = "photClam",
		type = "FLOAT",
		notNull = 1,
		displayOrder = 4;

	INSERT INTO md_Column
	SET columnId = 48, tableId = 4, name = "photBW",
		type = "FLOAT",
		notNull = 1,
		displayOrder = 5;

	INSERT INTO md_Index
	SET indexId = 9, tableId = 4,
		type = "PRIMARY KEY",
		columns = "filterId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 5, name = "MovingObject";

	INSERT INTO md_Column
	SET columnId = 49, tableId = 5, name = "movingObjectId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 50, tableId = 5, name = "movingObjectVersion",
		type = "INT",
		notNull = 1,
		defaultValue = "'1'",
		displayOrder = 2;

	INSERT INTO md_Column
	SET columnId = 51, tableId = 5, name = "procHistoryId",
		type = "INTEGER",
		notNull = 1,
		displayOrder = 3;

	INSERT INTO md_Column
	SET columnId = 52, tableId = 5, name = "taxonomicTypeId",
		type = "SMALLINT",
		notNull = 0,
		displayOrder = 4;

	INSERT INTO md_Column
	SET columnId = 53, tableId = 5, name = "ssmObjectName",
		type = "VARCHAR(32)",
		notNull = 0,
		displayOrder = 5;

	INSERT INTO md_Column
	SET columnId = 54, tableId = 5, name = "q",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 6;

	INSERT INTO md_Column
	SET columnId = 55, tableId = 5, name = "e",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 7;

	INSERT INTO md_Column
	SET columnId = 56, tableId = 5, name = "i",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 8;

	INSERT INTO md_Column
	SET columnId = 57, tableId = 5, name = "node",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 9;

	INSERT INTO md_Column
	SET columnId = 58, tableId = 5, name = "meanAnom",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 10;

	INSERT INTO md_Column
	SET columnId = 59, tableId = 5, name = "argPeri",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 11;

	INSERT INTO md_Column
	SET columnId = 60, tableId = 5, name = "distPeri",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 12;

	INSERT INTO md_Column
	SET columnId = 61, tableId = 5, name = "timePeri",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 13;

	INSERT INTO md_Column
	SET columnId = 62, tableId = 5, name = "epoch",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 14;

	INSERT INTO md_Column
	SET columnId = 63, tableId = 5, name = "h_v",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 15;

	INSERT INTO md_Column
	SET columnId = 64, tableId = 5, name = "g",
		type = "DOUBLE",
		notNull = 0,
		defaultValue = "0.15",
		displayOrder = 16;

	INSERT INTO md_Column
	SET columnId = 65, tableId = 5, name = "rotationPeriod",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 17;

	INSERT INTO md_Column
	SET columnId = 66, tableId = 5, name = "rotationEpoch",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 18;

	INSERT INTO md_Column
	SET columnId = 67, tableId = 5, name = "albedo",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 19;

	INSERT INTO md_Column
	SET columnId = 68, tableId = 5, name = "poleLat",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 20;

	INSERT INTO md_Column
	SET columnId = 69, tableId = 5, name = "poleLon",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 21;

	INSERT INTO md_Column
	SET columnId = 70, tableId = 5, name = "d3",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 22;

	INSERT INTO md_Column
	SET columnId = 71, tableId = 5, name = "d4",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 23;

	INSERT INTO md_Column
	SET columnId = 72, tableId = 5, name = "orbFitResidual",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 24;

	INSERT INTO md_Column
	SET columnId = 73, tableId = 5, name = "orbFitChi2",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 25;

	INSERT INTO md_Column
	SET columnId = 74, tableId = 5, name = "classification",
		type = "CHAR(1)",
		notNull = 0,
		displayOrder = 26;

	INSERT INTO md_Column
	SET columnId = 75, tableId = 5, name = "ssmId",
		type = "BIGINT",
		notNull = 0,
		displayOrder = 27;

	INSERT INTO md_Column
	SET columnId = 76, tableId = 5, name = "mopsStatus",
		type = "CHAR(1)",
		notNull = 0,
		displayOrder = 28;

	INSERT INTO md_Column
	SET columnId = 77, tableId = 5, name = "stablePass",
		type = "CHAR(1)",
		notNull = 0,
		displayOrder = 29;

	INSERT INTO md_Column
	SET columnId = 78, tableId = 5, name = "timeCreated",
		type = "TIMESTAMP",
		notNull = 0,
		displayOrder = 30;

	INSERT INTO md_Column
	SET columnId = 79, tableId = 5, name = "uMag",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 31;

	INSERT INTO md_Column
	SET columnId = 80, tableId = 5, name = "uMagErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 32;

	INSERT INTO md_Column
	SET columnId = 81, tableId = 5, name = "uAmplitude",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 33;

	INSERT INTO md_Column
	SET columnId = 82, tableId = 5, name = "uPeriod",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 34;

	INSERT INTO md_Column
	SET columnId = 83, tableId = 5, name = "gMag",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 35;

	INSERT INTO md_Column
	SET columnId = 84, tableId = 5, name = "gMagErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 36;

	INSERT INTO md_Column
	SET columnId = 85, tableId = 5, name = "gAmplitude",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 37;

	INSERT INTO md_Column
	SET columnId = 86, tableId = 5, name = "gPeriod",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 38;

	INSERT INTO md_Column
	SET columnId = 87, tableId = 5, name = "rMag",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 39;

	INSERT INTO md_Column
	SET columnId = 88, tableId = 5, name = "rMagErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 40;

	INSERT INTO md_Column
	SET columnId = 89, tableId = 5, name = "rAmplitude",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 41;

	INSERT INTO md_Column
	SET columnId = 90, tableId = 5, name = "rPeriod",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 42;

	INSERT INTO md_Column
	SET columnId = 91, tableId = 5, name = "iMag",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 43;

	INSERT INTO md_Column
	SET columnId = 92, tableId = 5, name = "iMagErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 44;

	INSERT INTO md_Column
	SET columnId = 93, tableId = 5, name = "iAmplitude",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 45;

	INSERT INTO md_Column
	SET columnId = 94, tableId = 5, name = "iPeriod",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 46;

	INSERT INTO md_Column
	SET columnId = 95, tableId = 5, name = "zMag",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 47;

	INSERT INTO md_Column
	SET columnId = 96, tableId = 5, name = "zMagErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 48;

	INSERT INTO md_Column
	SET columnId = 97, tableId = 5, name = "zAmplitude",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 49;

	INSERT INTO md_Column
	SET columnId = 98, tableId = 5, name = "zPeriod",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 50;

	INSERT INTO md_Column
	SET columnId = 99, tableId = 5, name = "yMag",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 51;

	INSERT INTO md_Column
	SET columnId = 100, tableId = 5, name = "yMagErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 52;

	INSERT INTO md_Column
	SET columnId = 101, tableId = 5, name = "yAmplitude",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 53;

	INSERT INTO md_Column
	SET columnId = 102, tableId = 5, name = "yPeriod",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 54;

	INSERT INTO md_Column
	SET columnId = 103, tableId = 5, name = "flag",
		type = "INTEGER",
		notNull = 0,
		displayOrder = 55;

	INSERT INTO md_Column
	SET columnId = 104, tableId = 5, name = "src01",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 56;

	INSERT INTO md_Column
	SET columnId = 105, tableId = 5, name = "src02",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 57;

	INSERT INTO md_Column
	SET columnId = 106, tableId = 5, name = "src03",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 58;

	INSERT INTO md_Column
	SET columnId = 107, tableId = 5, name = "src04",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 59;

	INSERT INTO md_Column
	SET columnId = 108, tableId = 5, name = "src05",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 60;

	INSERT INTO md_Column
	SET columnId = 109, tableId = 5, name = "src06",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 61;

	INSERT INTO md_Column
	SET columnId = 110, tableId = 5, name = "src07",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 62;

	INSERT INTO md_Column
	SET columnId = 111, tableId = 5, name = "src08",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 63;

	INSERT INTO md_Column
	SET columnId = 112, tableId = 5, name = "src09",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 64;

	INSERT INTO md_Column
	SET columnId = 113, tableId = 5, name = "src10",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 65;

	INSERT INTO md_Column
	SET columnId = 114, tableId = 5, name = "src11",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 66;

	INSERT INTO md_Column
	SET columnId = 115, tableId = 5, name = "src12",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 67;

	INSERT INTO md_Column
	SET columnId = 116, tableId = 5, name = "src13",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 68;

	INSERT INTO md_Column
	SET columnId = 117, tableId = 5, name = "src14",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 69;

	INSERT INTO md_Column
	SET columnId = 118, tableId = 5, name = "src15",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 70;

	INSERT INTO md_Column
	SET columnId = 119, tableId = 5, name = "src16",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 71;

	INSERT INTO md_Column
	SET columnId = 120, tableId = 5, name = "src17",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 72;

	INSERT INTO md_Column
	SET columnId = 121, tableId = 5, name = "src18",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 73;

	INSERT INTO md_Column
	SET columnId = 122, tableId = 5, name = "src19",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 74;

	INSERT INTO md_Column
	SET columnId = 123, tableId = 5, name = "src20",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 75;

	INSERT INTO md_Column
	SET columnId = 124, tableId = 5, name = "src21",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 76;

	INSERT INTO md_Column
	SET columnId = 125, tableId = 5, name = "convCode",
		type = "VARCHAR(8)",
		notNull = 0,
		displayOrder = 77;

	INSERT INTO md_Column
	SET columnId = 126, tableId = 5, name = "o_minus_c",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 78;

	INSERT INTO md_Column
	SET columnId = 127, tableId = 5, name = "moid1",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 79;

	INSERT INTO md_Column
	SET columnId = 128, tableId = 5, name = "moidLong1",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 80;

	INSERT INTO md_Column
	SET columnId = 129, tableId = 5, name = "moid2",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 81;

	INSERT INTO md_Column
	SET columnId = 130, tableId = 5, name = "moidLong2",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 82;

	INSERT INTO md_Column
	SET columnId = 131, tableId = 5, name = "arcLengthDays",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 83;

	INSERT INTO md_Index
	SET indexId = 10, tableId = 5,
		type = "PRIMARY KEY",
		columns = "movingObjectId, movingObjectVersion";

	INSERT INTO md_Index
	SET indexId = 11, tableId = 5,
		type = "-",
		columns = "procHistoryId";

	INSERT INTO md_Index
	SET indexId = 12, tableId = 5,
		type = "-",
		columns = "taxonomicTypeId";

	INSERT INTO md_Index
	SET indexId = 13, tableId = 5,
		type = "-",
		columns = "ssmId";

	INSERT INTO md_Index
	SET indexId = 14, tableId = 5,
		type = "-",
		columns = "ssmObjectName";

	INSERT INTO md_Index
	SET indexId = 15, tableId = 5,
		type = "-",
		columns = "mopsStatus";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 6, name = "Object",
	engine = "MyISAM";

	INSERT INTO md_Column
	SET columnId = 132, tableId = 6, name = "objectId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 133, tableId = 6, name = "ra",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Column
	SET columnId = 134, tableId = 6, name = "decl",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 3;

	INSERT INTO md_Column
	SET columnId = 135, tableId = 6, name = "earliestObsT",
		type = "DATETIME",
		notNull = 0,
		displayOrder = 4;

	INSERT INTO md_Column
	SET columnId = 136, tableId = 6, name = "latestObsT",
		type = "DATETIME",
		notNull = 0,
		displayOrder = 5;

	INSERT INTO md_Column
	SET columnId = 137, tableId = 6, name = "uMag",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 6;

	INSERT INTO md_Column
	SET columnId = 138, tableId = 6, name = "uMagErr",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 7;

	INSERT INTO md_Column
	SET columnId = 139, tableId = 6, name = "uPetroMag",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 8;

	INSERT INTO md_Column
	SET columnId = 140, tableId = 6, name = "uPetroMagErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 9;

	INSERT INTO md_Column
	SET columnId = 141, tableId = 6, name = "uIxx",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 10;

	INSERT INTO md_Column
	SET columnId = 142, tableId = 6, name = "uIyy",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 11;

	INSERT INTO md_Column
	SET columnId = 143, tableId = 6, name = "uIxy",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 12;

	INSERT INTO md_Column
	SET columnId = 144, tableId = 6, name = "uNumObs",
		type = "INTEGER",
		notNull = 0,
		displayOrder = 13;

	INSERT INTO md_Column
	SET columnId = 145, tableId = 6, name = "uFlags",
		type = "INTEGER",
		notNull = 0,
		displayOrder = 14;

	INSERT INTO md_Column
	SET columnId = 146, tableId = 6, name = "gMag",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 15;

	INSERT INTO md_Column
	SET columnId = 147, tableId = 6, name = "gMagErr",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 16;

	INSERT INTO md_Column
	SET columnId = 148, tableId = 6, name = "gPetroMag",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 17;

	INSERT INTO md_Column
	SET columnId = 149, tableId = 6, name = "gPetroMagErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 18;

	INSERT INTO md_Column
	SET columnId = 150, tableId = 6, name = "gIxx",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 19;

	INSERT INTO md_Column
	SET columnId = 151, tableId = 6, name = "gIyy",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 20;

	INSERT INTO md_Column
	SET columnId = 152, tableId = 6, name = "gIxy",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 21;

	INSERT INTO md_Column
	SET columnId = 153, tableId = 6, name = "gNumObs",
		type = "INTEGER",
		notNull = 0,
		displayOrder = 22;

	INSERT INTO md_Column
	SET columnId = 154, tableId = 6, name = "gFlags",
		type = "INTEGER",
		notNull = 0,
		displayOrder = 23;

	INSERT INTO md_Column
	SET columnId = 155, tableId = 6, name = "rMag",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 24;

	INSERT INTO md_Column
	SET columnId = 156, tableId = 6, name = "rMagErr",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 25;

	INSERT INTO md_Column
	SET columnId = 157, tableId = 6, name = "rPetroMag",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 26;

	INSERT INTO md_Column
	SET columnId = 158, tableId = 6, name = "rPetroMagErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 27;

	INSERT INTO md_Column
	SET columnId = 159, tableId = 6, name = "rIxx",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 28;

	INSERT INTO md_Column
	SET columnId = 160, tableId = 6, name = "rIyy",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 29;

	INSERT INTO md_Column
	SET columnId = 161, tableId = 6, name = "rIxy",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 30;

	INSERT INTO md_Column
	SET columnId = 162, tableId = 6, name = "rNumObs",
		type = "INTEGER",
		notNull = 0,
		displayOrder = 31;

	INSERT INTO md_Column
	SET columnId = 163, tableId = 6, name = "rFlags",
		type = "INTEGER",
		notNull = 0,
		displayOrder = 32;

	INSERT INTO md_Column
	SET columnId = 164, tableId = 6, name = "iMag",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 33;

	INSERT INTO md_Column
	SET columnId = 165, tableId = 6, name = "iMagErr",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 34;

	INSERT INTO md_Column
	SET columnId = 166, tableId = 6, name = "iPetroMag",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 35;

	INSERT INTO md_Column
	SET columnId = 167, tableId = 6, name = "iPetroMagErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 36;

	INSERT INTO md_Column
	SET columnId = 168, tableId = 6, name = "iIxx",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 37;

	INSERT INTO md_Column
	SET columnId = 169, tableId = 6, name = "iIyy",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 38;

	INSERT INTO md_Column
	SET columnId = 170, tableId = 6, name = "iIxy",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 39;

	INSERT INTO md_Column
	SET columnId = 171, tableId = 6, name = "iNumObs",
		type = "INTEGER",
		notNull = 0,
		displayOrder = 40;

	INSERT INTO md_Column
	SET columnId = 172, tableId = 6, name = "iFlags",
		type = "INTEGER",
		notNull = 0,
		displayOrder = 41;

	INSERT INTO md_Column
	SET columnId = 173, tableId = 6, name = "zMag",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 42;

	INSERT INTO md_Column
	SET columnId = 174, tableId = 6, name = "zMagErr",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 43;

	INSERT INTO md_Column
	SET columnId = 175, tableId = 6, name = "zPetroMag",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 44;

	INSERT INTO md_Column
	SET columnId = 176, tableId = 6, name = "zPetroMagErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 45;

	INSERT INTO md_Column
	SET columnId = 177, tableId = 6, name = "zIxx",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 46;

	INSERT INTO md_Column
	SET columnId = 178, tableId = 6, name = "zIyy",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 47;

	INSERT INTO md_Column
	SET columnId = 179, tableId = 6, name = "zIxy",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 48;

	INSERT INTO md_Column
	SET columnId = 180, tableId = 6, name = "zNumObs",
		type = "INTEGER",
		notNull = 0,
		displayOrder = 49;

	INSERT INTO md_Column
	SET columnId = 181, tableId = 6, name = "zFlags",
		type = "INTEGER",
		notNull = 0,
		displayOrder = 50;

	INSERT INTO md_Column
	SET columnId = 182, tableId = 6, name = "yMag",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 51;

	INSERT INTO md_Column
	SET columnId = 183, tableId = 6, name = "yMagErr",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 52;

	INSERT INTO md_Column
	SET columnId = 184, tableId = 6, name = "yPetroMag",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 53;

	INSERT INTO md_Column
	SET columnId = 185, tableId = 6, name = "yPetroMagErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 54;

	INSERT INTO md_Column
	SET columnId = 186, tableId = 6, name = "yIxx",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 55;

	INSERT INTO md_Column
	SET columnId = 187, tableId = 6, name = "yIyy",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 56;

	INSERT INTO md_Column
	SET columnId = 188, tableId = 6, name = "yIxy",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 57;

	INSERT INTO md_Column
	SET columnId = 189, tableId = 6, name = "yNumObs",
		type = "INTEGER",
		notNull = 0,
		displayOrder = 58;

	INSERT INTO md_Column
	SET columnId = 190, tableId = 6, name = "yFlags",
		type = "INTEGER",
		notNull = 0,
		displayOrder = 59;

	INSERT INTO md_Index
	SET indexId = 16, tableId = 6,
		type = "PRIMARY KEY",
		columns = "objectId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 7, name = "ObjectType";

	INSERT INTO md_Column
	SET columnId = 191, tableId = 7, name = "typeId",
		type = "SMALLINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 192, tableId = 7, name = "description",
		type = "VARCHAR(255)",
		notNull = 0,
		displayOrder = 2;

	INSERT INTO md_Index
	SET indexId = 17, tableId = 7,
		type = "PRIMARY KEY",
		columns = "typeId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 8, name = "Raw_Amp_Exposure";

	INSERT INTO md_Column
	SET columnId = 193, tableId = 8, name = "rawAmpExposureId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 194, tableId = 8, name = "rawCCDExposureId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Column
	SET columnId = 195, tableId = 8, name = "rawFPAExposureId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 3;

	INSERT INTO md_Column
	SET columnId = 196, tableId = 8, name = "ampId",
		type = "INTEGER",
		notNull = 1,
		displayOrder = 4;

	INSERT INTO md_Column
	SET columnId = 197, tableId = 8, name = "radecSys",
		type = "VARCHAR(20)",
		notNull = 0,
		displayOrder = 5;

	INSERT INTO md_Column
	SET columnId = 198, tableId = 8, name = "url",
		type = "VARCHAR(255)",
		notNull = 1,
		displayOrder = 6;

	INSERT INTO md_Column
	SET columnId = 199, tableId = 8, name = "ctype1",
		type = "VARCHAR(20)",
		notNull = 1,
		displayOrder = 7;

	INSERT INTO md_Column
	SET columnId = 200, tableId = 8, name = "ctype2",
		type = "VARCHAR(20)",
		notNull = 1,
		displayOrder = 8;

	INSERT INTO md_Column
	SET columnId = 201, tableId = 8, name = "crpix1",
		type = "FLOAT",
		notNull = 1,
		displayOrder = 9;

	INSERT INTO md_Column
	SET columnId = 202, tableId = 8, name = "crpix2",
		type = "FLOAT",
		notNull = 1,
		displayOrder = 10;

	INSERT INTO md_Column
	SET columnId = 203, tableId = 8, name = "crval1",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 11;

	INSERT INTO md_Column
	SET columnId = 204, tableId = 8, name = "crval2",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 12;

	INSERT INTO md_Column
	SET columnId = 205, tableId = 8, name = "cd11",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 13;

	INSERT INTO md_Column
	SET columnId = 206, tableId = 8, name = "cd21",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 14;

	INSERT INTO md_Column
	SET columnId = 207, tableId = 8, name = "cd12",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 15;

	INSERT INTO md_Column
	SET columnId = 208, tableId = 8, name = "cd22",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 16;

	INSERT INTO md_Column
	SET columnId = 209, tableId = 8, name = "taiObs",
		type = "TIMESTAMP",
		notNull = 1,
		defaultValue = "0",
		displayOrder = 17;

	INSERT INTO md_Column
	SET columnId = 210, tableId = 8, name = "darkTime",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 18;

	INSERT INTO md_Column
	SET columnId = 211, tableId = 8, name = "zd",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 19;

	INSERT INTO md_Index
	SET indexId = 18, tableId = 8,
		type = "PRIMARY KEY",
		columns = "rawAmpExposureId";

	INSERT INTO md_Index
	SET indexId = 19, tableId = 8,
		type = "-",
		columns = "rawFPAExposureId";

	INSERT INTO md_Index
	SET indexId = 20, tableId = 8,
		type = "-",
		columns = "rawCCDExposureId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 9, name = "Raw_CCD_Exposure";

	INSERT INTO md_Column
	SET columnId = 212, tableId = 9, name = "rawCCDExposureId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 213, tableId = 9, name = "rawFPAExposureId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Index
	SET indexId = 21, tableId = 9,
		type = "PRIMARY KEY",
		columns = "rawCCDExposureId";

	INSERT INTO md_Index
	SET indexId = 22, tableId = 9,
		type = "-",
		columns = "rawFPAExposureId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 10, name = "Raw_FPA_Exposure";

	INSERT INTO md_Column
	SET columnId = 214, tableId = 10, name = "rawFPAExposureId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 215, tableId = 10, name = "ra",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Column
	SET columnId = 216, tableId = 10, name = "decl",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 3;

	INSERT INTO md_Column
	SET columnId = 217, tableId = 10, name = "filterId",
		type = "INTEGER",
		notNull = 1,
		displayOrder = 4;

	INSERT INTO md_Column
	SET columnId = 218, tableId = 10, name = "equinox",
		type = "FLOAT",
		notNull = 1,
		displayOrder = 5;

	INSERT INTO md_Column
	SET columnId = 219, tableId = 10, name = "dateObs",
		type = "TIMESTAMP",
		notNull = 1,
		defaultValue = "0",
		displayOrder = 6;

	INSERT INTO md_Column
	SET columnId = 220, tableId = 10, name = "mjdObs",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 7;

	INSERT INTO md_Column
	SET columnId = 221, tableId = 10, name = "expTime",
		type = "FLOAT",
		notNull = 1,
		displayOrder = 8;

	INSERT INTO md_Column
	SET columnId = 222, tableId = 10, name = "airmass",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 9;

	INSERT INTO md_Index
	SET indexId = 23, tableId = 10,
		type = "PRIMARY KEY",
		columns = "rawFPAExposureId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 11, name = "Science_Amp_Exposure";

	INSERT INTO md_Column
	SET columnId = 223, tableId = 11, name = "scienceAmpExposureId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 224, tableId = 11, name = "scienceCCDExposureId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Column
	SET columnId = 225, tableId = 11, name = "scienceFPAExposureId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 3;

	INSERT INTO md_Column
	SET columnId = 226, tableId = 11, name = "rawAmpExposureId",
		type = "BIGINT",
		notNull = 0,
		displayOrder = 4;

	INSERT INTO md_Column
	SET columnId = 227, tableId = 11, name = "ampId",
		type = "INTEGER",
		notNull = 0,
		displayOrder = 5;

	INSERT INTO md_Column
	SET columnId = 228, tableId = 11, name = "filterId",
		type = "INTEGER",
		notNull = 0,
		displayOrder = 6;

	INSERT INTO md_Column
	SET columnId = 229, tableId = 11, name = "equinox",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 7;

	INSERT INTO md_Column
	SET columnId = 230, tableId = 11, name = "url",
		type = "VARCHAR(255)",
		notNull = 0,
		displayOrder = 8;

	INSERT INTO md_Column
	SET columnId = 231, tableId = 11, name = "ctype1",
		type = "VARCHAR(20)",
		notNull = 0,
		displayOrder = 9;

	INSERT INTO md_Column
	SET columnId = 232, tableId = 11, name = "ctype2",
		type = "VARCHAR(20)",
		notNull = 0,
		displayOrder = 10;

	INSERT INTO md_Column
	SET columnId = 233, tableId = 11, name = "crpix1",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 11;

	INSERT INTO md_Column
	SET columnId = 234, tableId = 11, name = "crpix2",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 12;

	INSERT INTO md_Column
	SET columnId = 235, tableId = 11, name = "crval1",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 13;

	INSERT INTO md_Column
	SET columnId = 236, tableId = 11, name = "crval2",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 14;

	INSERT INTO md_Column
	SET columnId = 237, tableId = 11, name = "cd1_1",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 15;

	INSERT INTO md_Column
	SET columnId = 238, tableId = 11, name = "cd2_1",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 16;

	INSERT INTO md_Column
	SET columnId = 239, tableId = 11, name = "cd1_2",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 17;

	INSERT INTO md_Column
	SET columnId = 240, tableId = 11, name = "cd2_2",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 18;

	INSERT INTO md_Column
	SET columnId = 241, tableId = 11, name = "dateObs",
		type = "TIMESTAMP",
		notNull = 0,
		defaultValue = "0",
		displayOrder = 19;

	INSERT INTO md_Column
	SET columnId = 242, tableId = 11, name = "expTime",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 20;

	INSERT INTO md_Column
	SET columnId = 243, tableId = 11, name = "ccdSize",
		type = "VARCHAR(50)",
		notNull = 0,
		displayOrder = 21;

	INSERT INTO md_Column
	SET columnId = 244, tableId = 11, name = "photoFlam",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 22;

	INSERT INTO md_Column
	SET columnId = 245, tableId = 11, name = "photoZP",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 23;

	INSERT INTO md_Column
	SET columnId = 246, tableId = 11, name = "nCombine",
		type = "INTEGER",
		notNull = 0,
		defaultValue = "1",
		displayOrder = 24;

	INSERT INTO md_Column
	SET columnId = 247, tableId = 11, name = "taiMjd",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 25;

	INSERT INTO md_Column
	SET columnId = 248, tableId = 11, name = "binX",
		type = "INTEGER",
		notNull = 0,
		displayOrder = 26;

	INSERT INTO md_Column
	SET columnId = 249, tableId = 11, name = "binY",
		type = "INTEGER",
		notNull = 0,
		displayOrder = 27;

	INSERT INTO md_Column
	SET columnId = 250, tableId = 11, name = "readNoise",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 28;

	INSERT INTO md_Column
	SET columnId = 251, tableId = 11, name = "saturationLimit",
		type = "BIGINT",
		notNull = 0,
		displayOrder = 29;

	INSERT INTO md_Column
	SET columnId = 252, tableId = 11, name = "dataSection",
		type = "VARCHAR(24)",
		notNull = 0,
		displayOrder = 30;

	INSERT INTO md_Column
	SET columnId = 253, tableId = 11, name = "gain",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 31;

	INSERT INTO md_Index
	SET indexId = 24, tableId = 11,
		type = "PRIMARY KEY",
		columns = "scienceAmpExposureId";

	INSERT INTO md_Index
	SET indexId = 25, tableId = 11,
		type = "-",
		columns = "scienceFPAExposureId";

	INSERT INTO md_Index
	SET indexId = 26, tableId = 11,
		type = "-",
		columns = "rawAmpExposureId";

	INSERT INTO md_Index
	SET indexId = 27, tableId = 11,
		type = "-",
		columns = "scienceCCDExposureId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 12, name = "Science_CCD_Exposure";

	INSERT INTO md_Column
	SET columnId = 254, tableId = 12, name = "scienceCCDExposureId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 255, tableId = 12, name = "scienceFPAExposureId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Column
	SET columnId = 256, tableId = 12, name = "rawCCDExposureId",
		type = "BIGINT",
		notNull = 0,
		displayOrder = 3;

	INSERT INTO md_Index
	SET indexId = 28, tableId = 12,
		type = "PRIMARY KEY",
		columns = "scienceCCDExposureId";

	INSERT INTO md_Index
	SET indexId = 29, tableId = 12,
		type = "-",
		columns = "rawCCDExposureId";

	INSERT INTO md_Index
	SET indexId = 30, tableId = 12,
		type = "-",
		columns = "scienceFPAExposureId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 13, name = "Science_FPA_Exposure";

	INSERT INTO md_Column
	SET columnId = 257, tableId = 13, name = "scienceFPAExposureId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Index
	SET indexId = 31, tableId = 13,
		type = "PRIMARY KEY",
		columns = "scienceFPAExposureId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 14, name = "Visit";

	INSERT INTO md_Column
	SET columnId = 258, tableId = 14, name = "visitId",
		type = "INTEGER",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 259, tableId = 14, name = "exposureId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Index
	SET indexId = 32, tableId = 14,
		type = "-",
		columns = "exposureId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 15, name = "WCSSource",
	engine = "MyISAM";

	INSERT INTO md_Column
	SET columnId = 260, tableId = 15, name = "wcsSourceId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 261, tableId = 15, name = "ampExposureId",
		type = "BIGINT",
		notNull = 0,
		displayOrder = 2;

	INSERT INTO md_Column
	SET columnId = 262, tableId = 15, name = "filterId",
		type = "TINYINT",
		notNull = 0,
		displayOrder = 3;

	INSERT INTO md_Column
	SET columnId = 263, tableId = 15, name = "wcsObjectId",
		type = "BIGINT",
		notNull = 0,
		displayOrder = 4;

	INSERT INTO md_Column
	SET columnId = 264, tableId = 15, name = "wcsObjectRa",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 5;

	INSERT INTO md_Column
	SET columnId = 265, tableId = 15, name = "wcsObjectRaErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 6;

	INSERT INTO md_Column
	SET columnId = 266, tableId = 15, name = "wcsObjectDecl",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 7;

	INSERT INTO md_Column
	SET columnId = 267, tableId = 15, name = "wcsObjectDeclErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 8;

	INSERT INTO md_Column
	SET columnId = 268, tableId = 15, name = "ra",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 9;

	INSERT INTO md_Column
	SET columnId = 269, tableId = 15, name = "raErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 10;

	INSERT INTO md_Column
	SET columnId = 270, tableId = 15, name = "decl",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 11;

	INSERT INTO md_Column
	SET columnId = 271, tableId = 15, name = "declErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 12;

	INSERT INTO md_Column
	SET columnId = 272, tableId = 15, name = "xFlux",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 13;

	INSERT INTO md_Column
	SET columnId = 273, tableId = 15, name = "xFluxErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 14;

	INSERT INTO md_Column
	SET columnId = 274, tableId = 15, name = "yFlux",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 15;

	INSERT INTO md_Column
	SET columnId = 275, tableId = 15, name = "yFluxErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 16;

	INSERT INTO md_Column
	SET columnId = 276, tableId = 15, name = "raFlux",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 17;

	INSERT INTO md_Column
	SET columnId = 277, tableId = 15, name = "raFluxErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 18;

	INSERT INTO md_Column
	SET columnId = 278, tableId = 15, name = "declFlux",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 19;

	INSERT INTO md_Column
	SET columnId = 279, tableId = 15, name = "declFluxErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 20;

	INSERT INTO md_Column
	SET columnId = 280, tableId = 15, name = "xPeak",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 21;

	INSERT INTO md_Column
	SET columnId = 281, tableId = 15, name = "yPeak",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 22;

	INSERT INTO md_Column
	SET columnId = 282, tableId = 15, name = "raPeak",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 23;

	INSERT INTO md_Column
	SET columnId = 283, tableId = 15, name = "declPeak",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 24;

	INSERT INTO md_Column
	SET columnId = 284, tableId = 15, name = "xAstrom",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 25;

	INSERT INTO md_Column
	SET columnId = 285, tableId = 15, name = "xAstromErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 26;

	INSERT INTO md_Column
	SET columnId = 286, tableId = 15, name = "yAstrom",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 27;

	INSERT INTO md_Column
	SET columnId = 287, tableId = 15, name = "yAstromErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 28;

	INSERT INTO md_Column
	SET columnId = 288, tableId = 15, name = "raAstrom",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 29;

	INSERT INTO md_Column
	SET columnId = 289, tableId = 15, name = "raAstromErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 30;

	INSERT INTO md_Column
	SET columnId = 290, tableId = 15, name = "declAstrom",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 31;

	INSERT INTO md_Column
	SET columnId = 291, tableId = 15, name = "declAstromErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 32;

	INSERT INTO md_Column
	SET columnId = 292, tableId = 15, name = "psfFlux",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 33;

	INSERT INTO md_Column
	SET columnId = 293, tableId = 15, name = "psfFluxErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 34;

	INSERT INTO md_Column
	SET columnId = 294, tableId = 15, name = "apFlux",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 35;

	INSERT INTO md_Column
	SET columnId = 295, tableId = 15, name = "apFluxErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 36;

	INSERT INTO md_Column
	SET columnId = 296, tableId = 15, name = "modelFlux",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 37;

	INSERT INTO md_Column
	SET columnId = 297, tableId = 15, name = "modelFluxErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 38;

	INSERT INTO md_Column
	SET columnId = 298, tableId = 15, name = "petroFlux",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 39;

	INSERT INTO md_Column
	SET columnId = 299, tableId = 15, name = "petroFluxErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 40;

	INSERT INTO md_Column
	SET columnId = 300, tableId = 15, name = "instFlux",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 41;

	INSERT INTO md_Column
	SET columnId = 301, tableId = 15, name = "instFluxErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 42;

	INSERT INTO md_Column
	SET columnId = 302, tableId = 15, name = "nonGrayCorrFlux",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 43;

	INSERT INTO md_Column
	SET columnId = 303, tableId = 15, name = "nonGrayCorrFluxErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 44;

	INSERT INTO md_Column
	SET columnId = 304, tableId = 15, name = "atmCorrFlux",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 45;

	INSERT INTO md_Column
	SET columnId = 305, tableId = 15, name = "atmCorrFluxErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 46;

	INSERT INTO md_Column
	SET columnId = 306, tableId = 15, name = "apDia",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 47;

	INSERT INTO md_Column
	SET columnId = 307, tableId = 15, name = "Ixx",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 48;

	INSERT INTO md_Column
	SET columnId = 308, tableId = 15, name = "IxxErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 49;

	INSERT INTO md_Column
	SET columnId = 309, tableId = 15, name = "Iyy",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 50;

	INSERT INTO md_Column
	SET columnId = 310, tableId = 15, name = "IyyErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 51;

	INSERT INTO md_Column
	SET columnId = 311, tableId = 15, name = "Ixy",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 52;

	INSERT INTO md_Column
	SET columnId = 312, tableId = 15, name = "IxyErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 53;

	INSERT INTO md_Column
	SET columnId = 313, tableId = 15, name = "snr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 54;

	INSERT INTO md_Column
	SET columnId = 314, tableId = 15, name = "chi2",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 55;

	INSERT INTO md_Column
	SET columnId = 315, tableId = 15, name = "sky",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 56;

	INSERT INTO md_Column
	SET columnId = 316, tableId = 15, name = "skyErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 57;

	INSERT INTO md_Column
	SET columnId = 317, tableId = 15, name = "flag",
		type = "BIGINT",
		notNull = 0,
		displayOrder = 58;

	INSERT INTO md_Index
	SET indexId = 33, tableId = 15,
		type = "PRIMARY KEY",
		columns = "wcsSourceId";

	INSERT INTO md_Index
	SET indexId = 34, tableId = 15,
		type = "-",
		columns = "ampExposureId";

	INSERT INTO md_Index
	SET indexId = 35, tableId = 15,
		type = "-",
		columns = "filterId";

	INSERT INTO md_Index
	SET indexId = 36, tableId = 15,
		type = "-",
		columns = "raErr";

	INSERT INTO md_Index
	SET indexId = 37, tableId = 15,
		type = "-",
		columns = "wcsObjectId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 16, name = "ZZZ_Db_Description",
	engine = "MyISAM",
	description = "Internal table used for storing database description";

	INSERT INTO md_Column
	SET columnId = 318, tableId = 16, name = "f",
		description = "The schema file name.",
		type = "VARCHAR(255),",
		notNull = 0,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 319, tableId = 16, name = "r",
		description = "Captures information from 'git describe'.",
		type = "VARCHAR(255)",
		notNull = 0,
		displayOrder = 2;

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 17, name = "_MovingObjectToType";

	INSERT INTO md_Column
	SET columnId = 320, tableId = 17, name = "movingObjectId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 321, tableId = 17, name = "typeId",
		type = "SMALLINT",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Column
	SET columnId = 322, tableId = 17, name = "probability",
		type = "TINYINT",
		notNull = 0,
		defaultValue = "100",
		displayOrder = 3;

	INSERT INTO md_Index
	SET indexId = 38, tableId = 17,
		type = "-",
		columns = "typeId";

	INSERT INTO md_Index
	SET indexId = 39, tableId = 17,
		type = "-",
		columns = "movingObjectId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 18, name = "_ObjectToType";

	INSERT INTO md_Column
	SET columnId = 323, tableId = 18, name = "objectId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 324, tableId = 18, name = "typeId",
		type = "SMALLINT",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Column
	SET columnId = 325, tableId = 18, name = "probability",
		type = "TINYINT",
		notNull = 0,
		defaultValue = "100",
		displayOrder = 3;

	INSERT INTO md_Index
	SET indexId = 40, tableId = 18,
		type = "-",
		columns = "typeId";

	INSERT INTO md_Index
	SET indexId = 41, tableId = 18,
		type = "-",
		columns = "objectId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 19, name = "_Raw_FPA_ExposureToVisit";

	INSERT INTO md_Column
	SET columnId = 326, tableId = 19, name = "visitId",
		type = "INTEGER",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 327, tableId = 19, name = "exposureId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Index
	SET indexId = 42, tableId = 19,
		type = "-",
		columns = "exposureId";

	INSERT INTO md_Index
	SET indexId = 43, tableId = 19,
		type = "-",
		columns = "exposureId";

	INSERT INTO md_Index
	SET indexId = 44, tableId = 19,
		type = "-",
		columns = "visitId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 20, name = "_Science_FPA_ExposureToTemplateImage";

	INSERT INTO md_Column
	SET columnId = 328, tableId = 20, name = "scienceFPAExposureId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 329, tableId = 20, name = "templateImageId",
		type = "INTEGER",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Index
	SET indexId = 45, tableId = 20,
		type = "-",
		columns = "scienceFPAExposureId";

	INSERT INTO md_Index
	SET indexId = 46, tableId = 20,
		type = "-",
		columns = "templateImageId";

	INSERT INTO md_Index
	SET indexId = 47, tableId = 20,
		type = "-",
		columns = "scienceFPAExposureId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 21, name = "_mops_Config";

	INSERT INTO md_Column
	SET columnId = 330, tableId = 21, name = "configId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 331, tableId = 21, name = "configText",
		type = "TEXT",
		notNull = 0,
		displayOrder = 2;

	INSERT INTO md_Index
	SET indexId = 48, tableId = 21,
		type = "PRIMARY KEY",
		columns = "configId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 22, name = "_mops_EonQueue";

	INSERT INTO md_Column
	SET columnId = 332, tableId = 22, name = "movingObjectId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 333, tableId = 22, name = "eventId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Column
	SET columnId = 334, tableId = 22, name = "insertTime",
		type = "TIMESTAMP",
		notNull = 1,
		displayOrder = 3;

	INSERT INTO md_Column
	SET columnId = 335, tableId = 22, name = "status",
		type = "CHAR(1)",
		notNull = 0,
		defaultValue = "'I'",
		displayOrder = 4;

	INSERT INTO md_Index
	SET indexId = 49, tableId = 22,
		type = "PRIMARY KEY",
		columns = "movingObjectId";

	INSERT INTO md_Index
	SET indexId = 50, tableId = 22,
		type = "-",
		columns = "movingObjectId";

	INSERT INTO md_Index
	SET indexId = 51, tableId = 22,
		type = "-",
		columns = "eventId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 23, name = "_mops_MoidQueue";

	INSERT INTO md_Column
	SET columnId = 336, tableId = 23, name = "movingObjectId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 337, tableId = 23, name = "movingObjectVersion",
		type = "INT",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Column
	SET columnId = 338, tableId = 23, name = "eventId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 3;

	INSERT INTO md_Column
	SET columnId = 339, tableId = 23, name = "insertTime",
		type = "TIMESTAMP",
		notNull = 1,
		defaultValue = "CURRENT_TIMESTAMP",
		displayOrder = 4;

	INSERT INTO md_Index
	SET indexId = 52, tableId = 23,
		type = "PRIMARY KEY",
		columns = "movingObjectId, movingObjectVersion";

	INSERT INTO md_Index
	SET indexId = 53, tableId = 23,
		type = "-",
		columns = "movingObjectId";

	INSERT INTO md_Index
	SET indexId = 54, tableId = 23,
		type = "-",
		columns = "eventId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 24, name = "_tmpl_Id";

	INSERT INTO md_Column
	SET columnId = 340, tableId = 24, name = "id",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 1;

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 25, name = "_tmpl_IdPair";

	INSERT INTO md_Column
	SET columnId = 341, tableId = 25, name = "first",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 342, tableId = 25, name = "second",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 2;

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 26, name = "_tmpl_MatchPair";

	INSERT INTO md_Column
	SET columnId = 343, tableId = 26, name = "first",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 344, tableId = 26, name = "second",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Column
	SET columnId = 345, tableId = 26, name = "distance",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 3;

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 27, name = "_tmpl_WCSSource",
	engine = "MyISAM";

	INSERT INTO md_Column
	SET columnId = 346, tableId = 27, name = "sourceId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 347, tableId = 27, name = "ampExposureId",
		type = "BIGINT",
		notNull = 0,
		displayOrder = 2;

	INSERT INTO md_Column
	SET columnId = 348, tableId = 27, name = "filterId",
		type = "TINYINT",
		notNull = 1,
		displayOrder = 3;

	INSERT INTO md_Column
	SET columnId = 349, tableId = 27, name = "objectId",
		type = "BIGINT",
		notNull = 0,
		displayOrder = 4;

	INSERT INTO md_Column
	SET columnId = 350, tableId = 27, name = "movingObjectId",
		type = "BIGINT",
		notNull = 0,
		displayOrder = 5;

	INSERT INTO md_Column
	SET columnId = 351, tableId = 27, name = "procHistoryId",
		type = "INTEGER",
		notNull = 1,
		displayOrder = 6;

	INSERT INTO md_Column
	SET columnId = 352, tableId = 27, name = "ra",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 7;

	INSERT INTO md_Column
	SET columnId = 353, tableId = 27, name = "raErrForDetection",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 8;

	INSERT INTO md_Column
	SET columnId = 354, tableId = 27, name = "raErrForWcs",
		type = "FLOAT",
		notNull = 1,
		displayOrder = 9;

	INSERT INTO md_Column
	SET columnId = 355, tableId = 27, name = "decl",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 10;

	INSERT INTO md_Column
	SET columnId = 356, tableId = 27, name = "declErrForDetection",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 11;

	INSERT INTO md_Column
	SET columnId = 357, tableId = 27, name = "declErrForWcs",
		type = "FLOAT",
		notNull = 1,
		displayOrder = 12;

	INSERT INTO md_Column
	SET columnId = 358, tableId = 27, name = "xFlux",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 13;

	INSERT INTO md_Column
	SET columnId = 359, tableId = 27, name = "xFluxErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 14;

	INSERT INTO md_Column
	SET columnId = 360, tableId = 27, name = "yFlux",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 15;

	INSERT INTO md_Column
	SET columnId = 361, tableId = 27, name = "yFluxErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 16;

	INSERT INTO md_Column
	SET columnId = 362, tableId = 27, name = "raFlux",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 17;

	INSERT INTO md_Column
	SET columnId = 363, tableId = 27, name = "raFluxErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 18;

	INSERT INTO md_Column
	SET columnId = 364, tableId = 27, name = "declFlux",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 19;

	INSERT INTO md_Column
	SET columnId = 365, tableId = 27, name = "declFluxErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 20;

	INSERT INTO md_Column
	SET columnId = 366, tableId = 27, name = "xPeak",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 21;

	INSERT INTO md_Column
	SET columnId = 367, tableId = 27, name = "yPeak",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 22;

	INSERT INTO md_Column
	SET columnId = 368, tableId = 27, name = "raPeak",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 23;

	INSERT INTO md_Column
	SET columnId = 369, tableId = 27, name = "declPeak",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 24;

	INSERT INTO md_Column
	SET columnId = 370, tableId = 27, name = "xAstrom",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 25;

	INSERT INTO md_Column
	SET columnId = 371, tableId = 27, name = "xAstromErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 26;

	INSERT INTO md_Column
	SET columnId = 372, tableId = 27, name = "yAstrom",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 27;

	INSERT INTO md_Column
	SET columnId = 373, tableId = 27, name = "yAstromErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 28;

	INSERT INTO md_Column
	SET columnId = 374, tableId = 27, name = "raAstrom",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 29;

	INSERT INTO md_Column
	SET columnId = 375, tableId = 27, name = "raAstromErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 30;

	INSERT INTO md_Column
	SET columnId = 376, tableId = 27, name = "declAstrom",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 31;

	INSERT INTO md_Column
	SET columnId = 377, tableId = 27, name = "declAstromErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 32;

	INSERT INTO md_Column
	SET columnId = 378, tableId = 27, name = "taiMidPoint",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 33;

	INSERT INTO md_Column
	SET columnId = 379, tableId = 27, name = "taiRange",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 34;

	INSERT INTO md_Column
	SET columnId = 380, tableId = 27, name = "psfFlux",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 35;

	INSERT INTO md_Column
	SET columnId = 381, tableId = 27, name = "psfFluxErr",
		type = "FLOAT",
		notNull = 1,
		displayOrder = 36;

	INSERT INTO md_Column
	SET columnId = 382, tableId = 27, name = "apFlux",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 37;

	INSERT INTO md_Column
	SET columnId = 383, tableId = 27, name = "apFluxErr",
		type = "FLOAT",
		notNull = 1,
		displayOrder = 38;

	INSERT INTO md_Column
	SET columnId = 384, tableId = 27, name = "modelFlux",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 39;

	INSERT INTO md_Column
	SET columnId = 385, tableId = 27, name = "modelFluxErr",
		type = "FLOAT",
		notNull = 1,
		displayOrder = 40;

	INSERT INTO md_Column
	SET columnId = 386, tableId = 27, name = "petroFlux",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 41;

	INSERT INTO md_Column
	SET columnId = 387, tableId = 27, name = "petroFluxErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 42;

	INSERT INTO md_Column
	SET columnId = 388, tableId = 27, name = "instFlux",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 43;

	INSERT INTO md_Column
	SET columnId = 389, tableId = 27, name = "instFluxErr",
		type = "FLOAT",
		notNull = 1,
		displayOrder = 44;

	INSERT INTO md_Column
	SET columnId = 390, tableId = 27, name = "nonGrayCorrFlux",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 45;

	INSERT INTO md_Column
	SET columnId = 391, tableId = 27, name = "nonGrayCorrFluxErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 46;

	INSERT INTO md_Column
	SET columnId = 392, tableId = 27, name = "atmCorrFlux",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 47;

	INSERT INTO md_Column
	SET columnId = 393, tableId = 27, name = "atmCorrFluxErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 48;

	INSERT INTO md_Column
	SET columnId = 394, tableId = 27, name = "apDia",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 49;

	INSERT INTO md_Column
	SET columnId = 395, tableId = 27, name = "Ixx",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 50;

	INSERT INTO md_Column
	SET columnId = 396, tableId = 27, name = "IxxErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 51;

	INSERT INTO md_Column
	SET columnId = 397, tableId = 27, name = "Iyy",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 52;

	INSERT INTO md_Column
	SET columnId = 398, tableId = 27, name = "IyyErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 53;

	INSERT INTO md_Column
	SET columnId = 399, tableId = 27, name = "Ixy",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 54;

	INSERT INTO md_Column
	SET columnId = 400, tableId = 27, name = "IxyErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 55;

	INSERT INTO md_Column
	SET columnId = 401, tableId = 27, name = "snr",
		type = "FLOAT",
		notNull = 1,
		displayOrder = 56;

	INSERT INTO md_Column
	SET columnId = 402, tableId = 27, name = "chi2",
		type = "FLOAT",
		notNull = 1,
		displayOrder = 57;

	INSERT INTO md_Column
	SET columnId = 403, tableId = 27, name = "sky",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 58;

	INSERT INTO md_Column
	SET columnId = 404, tableId = 27, name = "skyErr",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 59;

	INSERT INTO md_Column
	SET columnId = 405, tableId = 27, name = "flagForAssociation",
		type = "SMALLINT",
		notNull = 0,
		displayOrder = 60;

	INSERT INTO md_Column
	SET columnId = 406, tableId = 27, name = "flagForDetection",
		type = "SMALLINT",
		notNull = 0,
		displayOrder = 61;

	INSERT INTO md_Column
	SET columnId = 407, tableId = 27, name = "flagForWcs",
		type = "SMALLINT",
		notNull = 0,
		displayOrder = 62;

	INSERT INTO md_Index
	SET indexId = 55, tableId = 27,
		type = "PRIMARY KEY",
		columns = "sourceId";

	INSERT INTO md_Index
	SET indexId = 56, tableId = 27,
		type = "-",
		columns = "ampExposureId";

	INSERT INTO md_Index
	SET indexId = 57, tableId = 27,
		type = "-",
		columns = "filterId";

	INSERT INTO md_Index
	SET indexId = 58, tableId = 27,
		type = "-",
		columns = "movingObjectId";

	INSERT INTO md_Index
	SET indexId = 59, tableId = 27,
		type = "-",
		columns = "objectId";

	INSERT INTO md_Index
	SET indexId = 60, tableId = 27,
		type = "-",
		columns = "procHistoryId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 28, name = "_tmpl_mops_Ephemeris",
	engine = "MyISAM";

	INSERT INTO md_Column
	SET columnId = 408, tableId = 28, name = "movingObjectId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 409, tableId = 28, name = "movingObjectVersion",
		type = "INTEGER",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Column
	SET columnId = 410, tableId = 28, name = "ra",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 3;

	INSERT INTO md_Column
	SET columnId = 411, tableId = 28, name = "decl",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 4;

	INSERT INTO md_Column
	SET columnId = 412, tableId = 28, name = "mjd",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 5;

	INSERT INTO md_Column
	SET columnId = 413, tableId = 28, name = "smia",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 6;

	INSERT INTO md_Column
	SET columnId = 414, tableId = 28, name = "smaa",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 7;

	INSERT INTO md_Column
	SET columnId = 415, tableId = 28, name = "pa",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 8;

	INSERT INTO md_Column
	SET columnId = 416, tableId = 28, name = "mag",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 9;

	INSERT INTO md_Index
	SET indexId = 61, tableId = 28,
		type = "-",
		columns = "movingObjectId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 29, name = "_tmpl_mops_Prediction",
	engine = "MyISAM";

	INSERT INTO md_Column
	SET columnId = 417, tableId = 29, name = "movingObjectId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 418, tableId = 29, name = "movingObjectVersion",
		type = "INTEGER",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Column
	SET columnId = 419, tableId = 29, name = "ra",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 3;

	INSERT INTO md_Column
	SET columnId = 420, tableId = 29, name = "decl",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 4;

	INSERT INTO md_Column
	SET columnId = 421, tableId = 29, name = "mjd",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 5;

	INSERT INTO md_Column
	SET columnId = 422, tableId = 29, name = "smia",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 6;

	INSERT INTO md_Column
	SET columnId = 423, tableId = 29, name = "smaa",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 7;

	INSERT INTO md_Column
	SET columnId = 424, tableId = 29, name = "pa",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 8;

	INSERT INTO md_Column
	SET columnId = 425, tableId = 29, name = "mag",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 9;

	INSERT INTO md_Column
	SET columnId = 426, tableId = 29, name = "magErr",
		type = "FLOAT",
		notNull = 1,
		displayOrder = 10;

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 30, name = "mops_Event";

	INSERT INTO md_Column
	SET columnId = 427, tableId = 30, name = "eventId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 428, tableId = 30, name = "procHistoryId",
		type = "INT",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Column
	SET columnId = 429, tableId = 30, name = "eventType",
		type = "CHAR(1)",
		notNull = 1,
		displayOrder = 3;

	INSERT INTO md_Column
	SET columnId = 430, tableId = 30, name = "eventTime",
		type = "TIMESTAMP",
		notNull = 1,
		defaultValue = "CURRENT_TIMESTAMP",
		displayOrder = 4;

	INSERT INTO md_Column
	SET columnId = 431, tableId = 30, name = "movingObjectId",
		type = "BIGINT",
		notNull = 0,
		displayOrder = 5;

	INSERT INTO md_Column
	SET columnId = 432, tableId = 30, name = "movingObjectVersion",
		type = "INT",
		notNull = 0,
		displayOrder = 6;

	INSERT INTO md_Column
	SET columnId = 433, tableId = 30, name = "orbitCode",
		type = "CHAR(1)",
		notNull = 0,
		displayOrder = 7;

	INSERT INTO md_Column
	SET columnId = 434, tableId = 30, name = "d3",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 8;

	INSERT INTO md_Column
	SET columnId = 435, tableId = 30, name = "d4",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 9;

	INSERT INTO md_Column
	SET columnId = 436, tableId = 30, name = "ccdExposureId",
		type = "BIGINT",
		notNull = 0,
		displayOrder = 10;

	INSERT INTO md_Column
	SET columnId = 437, tableId = 30, name = "classification",
		type = "CHAR(1)",
		notNull = 0,
		displayOrder = 11;

	INSERT INTO md_Column
	SET columnId = 438, tableId = 30, name = "ssmId",
		type = "BIGINT",
		notNull = 0,
		displayOrder = 12;

	INSERT INTO md_Index
	SET indexId = 62, tableId = 30,
		type = "PRIMARY KEY",
		columns = "eventId";

	INSERT INTO md_Index
	SET indexId = 63, tableId = 30,
		type = "-",
		columns = "movingObjectId";

	INSERT INTO md_Index
	SET indexId = 64, tableId = 30,
		type = "-",
		columns = "ccdExposureId";

	INSERT INTO md_Index
	SET indexId = 65, tableId = 30,
		type = "-",
		columns = "movingObjectIdASC, movingObjectVersion";

	INSERT INTO md_Index
	SET indexId = 66, tableId = 30,
		type = "-",
		columns = "procHistoryId";

	INSERT INTO md_Index
	SET indexId = 67, tableId = 30,
		type = "-",
		columns = "ssmId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 31, name = "mops_Event_OrbitDerivation";

	INSERT INTO md_Column
	SET columnId = 439, tableId = 31, name = "eventId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 440, tableId = 31, name = "trackletId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Index
	SET indexId = 68, tableId = 31,
		type = "PRIMARY KEY",
		columns = "eventId, trackletId";

	INSERT INTO md_Index
	SET indexId = 69, tableId = 31,
		type = "-",
		columns = "trackletId";

	INSERT INTO md_Index
	SET indexId = 70, tableId = 31,
		type = "-",
		columns = "eventId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 32, name = "mops_Event_OrbitIdentification";

	INSERT INTO md_Column
	SET columnId = 441, tableId = 32, name = "eventId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 442, tableId = 32, name = "childObjectId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Index
	SET indexId = 71, tableId = 32,
		type = "PRIMARY KEY",
		columns = "eventId";

	INSERT INTO md_Index
	SET indexId = 72, tableId = 32,
		type = "-",
		columns = "childObjectId";

	INSERT INTO md_Index
	SET indexId = 73, tableId = 32,
		type = "-",
		columns = "eventId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 33, name = "mops_Event_TrackletAttribution";

	INSERT INTO md_Column
	SET columnId = 443, tableId = 33, name = "eventId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 444, tableId = 33, name = "trackletId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Column
	SET columnId = 445, tableId = 33, name = "ephemerisDistance",
		type = "FLOAT",
		notNull = 1,
		displayOrder = 3;

	INSERT INTO md_Column
	SET columnId = 446, tableId = 33, name = "ephemerisUncertainty",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 4;

	INSERT INTO md_Index
	SET indexId = 74, tableId = 33,
		type = "PRIMARY KEY",
		columns = "eventId";

	INSERT INTO md_Index
	SET indexId = 75, tableId = 33,
		type = "-",
		columns = "trackletId";

	INSERT INTO md_Index
	SET indexId = 76, tableId = 33,
		type = "-",
		columns = "eventId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 34, name = "mops_Event_TrackletPrecovery";

	INSERT INTO md_Column
	SET columnId = 447, tableId = 34, name = "eventId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 448, tableId = 34, name = "trackletId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Column
	SET columnId = 449, tableId = 34, name = "ephemerisDistance",
		type = "FLOAT",
		notNull = 1,
		displayOrder = 3;

	INSERT INTO md_Column
	SET columnId = 450, tableId = 34, name = "ephemerisUncertainty",
		type = "FLOAT",
		notNull = 0,
		displayOrder = 4;

	INSERT INTO md_Index
	SET indexId = 77, tableId = 34,
		type = "PRIMARY KEY",
		columns = "eventId";

	INSERT INTO md_Index
	SET indexId = 78, tableId = 34,
		type = "-",
		columns = "trackletId";

	INSERT INTO md_Index
	SET indexId = 79, tableId = 34,
		type = "-",
		columns = "eventId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 35, name = "mops_Event_TrackletRemoval";

	INSERT INTO md_Column
	SET columnId = 451, tableId = 35, name = "eventId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 452, tableId = 35, name = "trackletId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Index
	SET indexId = 80, tableId = 35,
		type = "PRIMARY KEY",
		columns = "eventId";

	INSERT INTO md_Index
	SET indexId = 81, tableId = 35,
		type = "-",
		columns = "trackletId";

	INSERT INTO md_Index
	SET indexId = 82, tableId = 35,
		type = "-",
		columns = "eventId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 36, name = "mops_MovingObjectToTracklet";

	INSERT INTO md_Column
	SET columnId = 453, tableId = 36, name = "movingObjectId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 454, tableId = 36, name = "trackletId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Index
	SET indexId = 83, tableId = 36,
		type = "-",
		columns = "movingObjectId";

	INSERT INTO md_Index
	SET indexId = 84, tableId = 36,
		type = "-",
		columns = "trackletId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 37, name = "mops_SSM";

	INSERT INTO md_Column
	SET columnId = 455, tableId = 37, name = "ssmId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 456, tableId = 37, name = "ssmDescId",
		type = "SMALLINT",
		notNull = 0,
		displayOrder = 2;

	INSERT INTO md_Column
	SET columnId = 457, tableId = 37, name = "q",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 3;

	INSERT INTO md_Column
	SET columnId = 458, tableId = 37, name = "e",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 4;

	INSERT INTO md_Column
	SET columnId = 459, tableId = 37, name = "i",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 5;

	INSERT INTO md_Column
	SET columnId = 460, tableId = 37, name = "node",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 6;

	INSERT INTO md_Column
	SET columnId = 461, tableId = 37, name = "argPeri",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 7;

	INSERT INTO md_Column
	SET columnId = 462, tableId = 37, name = "timePeri",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 8;

	INSERT INTO md_Column
	SET columnId = 463, tableId = 37, name = "epoch",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 9;

	INSERT INTO md_Column
	SET columnId = 464, tableId = 37, name = "h_v",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 10;

	INSERT INTO md_Column
	SET columnId = 465, tableId = 37, name = "h_ss",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 11;

	INSERT INTO md_Column
	SET columnId = 466, tableId = 37, name = "g",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 12;

	INSERT INTO md_Column
	SET columnId = 467, tableId = 37, name = "albedo",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 13;

	INSERT INTO md_Column
	SET columnId = 468, tableId = 37, name = "ssmObjectName",
		type = "VARCHAR(32)",
		notNull = 1,
		displayOrder = 14;

	INSERT INTO md_Index
	SET indexId = 85, tableId = 37,
		type = "PRIMARY KEY",
		columns = "ssmId";

	INSERT INTO md_Index
	SET indexId = 86, tableId = 37,
		type = "UNIQUE",
		columns = "ssmObjectName";

	INSERT INTO md_Index
	SET indexId = 87, tableId = 37,
		type = "-",
		columns = "ssmDescId";

	INSERT INTO md_Index
	SET indexId = 88, tableId = 37,
		type = "-",
		columns = "epoch";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 38, name = "mops_SSMDesc";

	INSERT INTO md_Column
	SET columnId = 469, tableId = 38, name = "ssmDescId",
		type = "SMALLINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 470, tableId = 38, name = "prefix",
		type = "CHAR(4)",
		notNull = 0,
		displayOrder = 2;

	INSERT INTO md_Column
	SET columnId = 471, tableId = 38, name = "description",
		type = "VARCHAR(100)",
		notNull = 0,
		displayOrder = 3;

	INSERT INTO md_Index
	SET indexId = 89, tableId = 38,
		type = "PRIMARY KEY",
		columns = "ssmDescId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 39, name = "mops_Tracklet";

	INSERT INTO md_Column
	SET columnId = 472, tableId = 39, name = "trackletId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 473, tableId = 39, name = "ccdExposureId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Column
	SET columnId = 474, tableId = 39, name = "procHistoryId",
		type = "INT",
		notNull = 1,
		displayOrder = 3;

	INSERT INTO md_Column
	SET columnId = 475, tableId = 39, name = "ssmId",
		type = "BIGINT",
		notNull = 0,
		displayOrder = 4;

	INSERT INTO md_Column
	SET columnId = 476, tableId = 39, name = "velRa",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 5;

	INSERT INTO md_Column
	SET columnId = 477, tableId = 39, name = "velRaErr",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 6;

	INSERT INTO md_Column
	SET columnId = 478, tableId = 39, name = "velDecl",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 7;

	INSERT INTO md_Column
	SET columnId = 479, tableId = 39, name = "velDeclErr",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 8;

	INSERT INTO md_Column
	SET columnId = 480, tableId = 39, name = "velTot",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 9;

	INSERT INTO md_Column
	SET columnId = 481, tableId = 39, name = "accRa",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 10;

	INSERT INTO md_Column
	SET columnId = 482, tableId = 39, name = "accRaErr",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 11;

	INSERT INTO md_Column
	SET columnId = 483, tableId = 39, name = "accDecl",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 12;

	INSERT INTO md_Column
	SET columnId = 484, tableId = 39, name = "accDeclErr",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 13;

	INSERT INTO md_Column
	SET columnId = 485, tableId = 39, name = "extEpoch",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 14;

	INSERT INTO md_Column
	SET columnId = 486, tableId = 39, name = "extRa",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 15;

	INSERT INTO md_Column
	SET columnId = 487, tableId = 39, name = "extRaErr",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 16;

	INSERT INTO md_Column
	SET columnId = 488, tableId = 39, name = "extDecl",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 17;

	INSERT INTO md_Column
	SET columnId = 489, tableId = 39, name = "extDeclErr",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 18;

	INSERT INTO md_Column
	SET columnId = 490, tableId = 39, name = "extMag",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 19;

	INSERT INTO md_Column
	SET columnId = 491, tableId = 39, name = "extMagErr",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 20;

	INSERT INTO md_Column
	SET columnId = 492, tableId = 39, name = "probability",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 21;

	INSERT INTO md_Column
	SET columnId = 493, tableId = 39, name = "status",
		type = "CHAR(1)",
		notNull = 0,
		displayOrder = 22;

	INSERT INTO md_Column
	SET columnId = 494, tableId = 39, name = "classification",
		type = "CHAR(1)",
		notNull = 0,
		displayOrder = 23;

	INSERT INTO md_Index
	SET indexId = 90, tableId = 39,
		type = "PRIMARY KEY",
		columns = "trackletId";

	INSERT INTO md_Index
	SET indexId = 91, tableId = 39,
		type = "-",
		columns = "ccdExposureId";

	INSERT INTO md_Index
	SET indexId = 92, tableId = 39,
		type = "-",
		columns = "ssmId";

	INSERT INTO md_Index
	SET indexId = 93, tableId = 39,
		type = "-",
		columns = "classification";

	INSERT INTO md_Index
	SET indexId = 94, tableId = 39,
		type = "-",
		columns = "extEpoch";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 40, name = "mops_TrackletsToDIASource";

	INSERT INTO md_Column
	SET columnId = 495, tableId = 40, name = "trackletId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 496, tableId = 40, name = "diaSourceId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Index
	SET indexId = 95, tableId = 40,
		type = "PRIMARY KEY",
		columns = "trackletId, diaSourceId";

	INSERT INTO md_Index
	SET indexId = 96, tableId = 40,
		type = "-",
		columns = "diaSourceId";

	INSERT INTO md_Index
	SET indexId = 97, tableId = 40,
		type = "-",
		columns = "trackletId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 41, name = "prv_Filter",
	engine = "MyISAM";

	INSERT INTO md_Column
	SET columnId = 497, tableId = 41, name = "filterId",
		type = "TINYINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 498, tableId = 41, name = "focalPlaneId",
		type = "TINYINT",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Column
	SET columnId = 499, tableId = 41, name = "name",
		type = "VARCHAR(80)",
		notNull = 1,
		displayOrder = 3;

	INSERT INTO md_Column
	SET columnId = 500, tableId = 41, name = "url",
		type = "VARCHAR(255)",
		notNull = 0,
		displayOrder = 4;

	INSERT INTO md_Column
	SET columnId = 501, tableId = 41, name = "clam",
		type = "FLOAT",
		notNull = 1,
		displayOrder = 5;

	INSERT INTO md_Column
	SET columnId = 502, tableId = 41, name = "bw",
		type = "FLOAT",
		notNull = 1,
		displayOrder = 6;

	INSERT INTO md_Index
	SET indexId = 98, tableId = 41,
		type = "PRIMARY KEY",
		columns = "filterId";

	INSERT INTO md_Index
	SET indexId = 99, tableId = 41,
		type = "UNIQUE",
		columns = "name";

	INSERT INTO md_Index
	SET indexId = 100, tableId = 41,
		type = "-",
		columns = "focalPlaneId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 42, name = "prv_PolicyFile";

	INSERT INTO md_Column
	SET columnId = 503, tableId = 42, name = "policyFileId",
		type = "INTEGER",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 504, tableId = 42, name = "pathName",
		type = "VARCHAR(255)",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Column
	SET columnId = 505, tableId = 42, name = "hashValue",
		type = "CHAR(32)",
		notNull = 1,
		displayOrder = 3;

	INSERT INTO md_Column
	SET columnId = 506, tableId = 42, name = "modifiedDate",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 4;

	INSERT INTO md_Index
	SET indexId = 101, tableId = 42,
		type = "PRIMARY KEY",
		columns = "policyFileId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 43, name = "prv_PolicyKey";

	INSERT INTO md_Column
	SET columnId = 507, tableId = 43, name = "policyKeyId",
		type = "INTEGER",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 508, tableId = 43, name = "policyFileId",
		type = "INTEGER",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Column
	SET columnId = 509, tableId = 43, name = "keyName",
		type = "VARCHAR(255)",
		notNull = 1,
		displayOrder = 3;

	INSERT INTO md_Column
	SET columnId = 510, tableId = 43, name = "keyType",
		type = "VARCHAR(16)",
		notNull = 1,
		displayOrder = 4;

	INSERT INTO md_Index
	SET indexId = 102, tableId = 43,
		type = "PRIMARY KEY",
		columns = "policyKeyId";

	INSERT INTO md_Index
	SET indexId = 103, tableId = 43,
		type = "-",
		columns = "policyFileId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 44, name = "prv_Run";

	INSERT INTO md_Column
	SET columnId = 511, tableId = 44, name = "offset",
		type = "INTEGER",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 512, tableId = 44, name = "runId",
		type = "VARCHAR(255)",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Index
	SET indexId = 104, tableId = 44,
		type = "PRIMARY KEY",
		columns = "offset";

	INSERT INTO md_Index
	SET indexId = 105, tableId = 44,
		type = "UNIQUE",
		columns = "runId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 45, name = "prv_SoftwarePackage";

	INSERT INTO md_Column
	SET columnId = 513, tableId = 45, name = "packageId",
		type = "INTEGER",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 514, tableId = 45, name = "packageName",
		type = "VARCHAR(64)",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Index
	SET indexId = 106, tableId = 45,
		type = "PRIMARY KEY",
		columns = "packageId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 46, name = "prv_cnf_PolicyKey";

	INSERT INTO md_Column
	SET columnId = 515, tableId = 46, name = "policyKeyId",
		type = "INTEGER",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 516, tableId = 46, name = "value",
		type = "TEXT",
		notNull = 0,
		displayOrder = 2;

	INSERT INTO md_Column
	SET columnId = 517, tableId = 46, name = "validityBegin",
		type = "DATETIME",
		notNull = 0,
		displayOrder = 3;

	INSERT INTO md_Column
	SET columnId = 518, tableId = 46, name = "validityEnd",
		type = "DATETIME",
		notNull = 0,
		displayOrder = 4;

	INSERT INTO md_Index
	SET indexId = 107, tableId = 46,
		type = "PRIMARY KEY",
		columns = "policyKeyId";

	INSERT INTO md_Index
	SET indexId = 108, tableId = 46,
		type = "-",
		columns = "policyKeyId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 47, name = "prv_cnf_SoftwarePackage";

	INSERT INTO md_Column
	SET columnId = 519, tableId = 47, name = "packageId",
		type = "INTEGER",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 520, tableId = 47, name = "version",
		type = "VARCHAR(255)",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Column
	SET columnId = 521, tableId = 47, name = "directory",
		type = "VARCHAR(255)",
		notNull = 1,
		displayOrder = 3;

	INSERT INTO md_Column
	SET columnId = 522, tableId = 47, name = "validityBegin",
		type = "DATETIME",
		notNull = 0,
		displayOrder = 4;

	INSERT INTO md_Column
	SET columnId = 523, tableId = 47, name = "validityEnd",
		type = "DATETIME",
		notNull = 0,
		displayOrder = 5;

	INSERT INTO md_Index
	SET indexId = 109, tableId = 47,
		type = "PRIMARY KEY",
		columns = "packageId";

	INSERT INTO md_Index
	SET indexId = 110, tableId = 47,
		type = "-",
		columns = "packageId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 48, name = "sdqa_ImageStatus";

	INSERT INTO md_Column
	SET columnId = 524, tableId = 48, name = "sdqa_imageStatusId",
		type = "SMALLINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 525, tableId = 48, name = "statusName",
		type = "VARCHAR(30)",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Column
	SET columnId = 526, tableId = 48, name = "definition",
		type = "VARCHAR(255)",
		notNull = 1,
		displayOrder = 3;

	INSERT INTO md_Index
	SET indexId = 111, tableId = 48,
		type = "PRIMARY KEY",
		columns = "sdqa_imageStatusId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 49, name = "sdqa_Metric";

	INSERT INTO md_Column
	SET columnId = 527, tableId = 49, name = "sdqa_metricId",
		type = "SMALLINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 528, tableId = 49, name = "metricName",
		type = "VARCHAR(30)",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Column
	SET columnId = 529, tableId = 49, name = "physicalUnits",
		type = "VARCHAR(30)",
		notNull = 1,
		displayOrder = 3;

	INSERT INTO md_Column
	SET columnId = 530, tableId = 49, name = "dataType",
		type = "CHAR(1)",
		notNull = 1,
		displayOrder = 4;

	INSERT INTO md_Column
	SET columnId = 531, tableId = 49, name = "definition",
		type = "VARCHAR(255)",
		notNull = 1,
		displayOrder = 5;

	INSERT INTO md_Index
	SET indexId = 112, tableId = 49,
		type = "PRIMARY KEY",
		columns = "sdqa_metricId";

	INSERT INTO md_Index
	SET indexId = 113, tableId = 49,
		type = "UNIQUE",
		columns = "metricName";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 50, name = "sdqa_Rating_ForScienceAmpExposure";

	INSERT INTO md_Column
	SET columnId = 532, tableId = 50, name = "sdqa_ratingId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 533, tableId = 50, name = "sdqa_metricId",
		type = "SMALLINT",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Column
	SET columnId = 534, tableId = 50, name = "sdqa_thresholdId",
		type = "SMALLINT",
		notNull = 1,
		displayOrder = 3;

	INSERT INTO md_Column
	SET columnId = 535, tableId = 50, name = "ampExposureId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 4;

	INSERT INTO md_Column
	SET columnId = 536, tableId = 50, name = "metricValue",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 5;

	INSERT INTO md_Column
	SET columnId = 537, tableId = 50, name = "metricErr",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 6;

	INSERT INTO md_Index
	SET indexId = 114, tableId = 50,
		type = "PRIMARY KEY",
		columns = "sdqa_ratingId";

	INSERT INTO md_Index
	SET indexId = 115, tableId = 50,
		type = "UNIQUE",
		columns = "sdqa_metricId, ampExposureId";

	INSERT INTO md_Index
	SET indexId = 116, tableId = 50,
		type = "-",
		columns = "sdqa_metricId";

	INSERT INTO md_Index
	SET indexId = 117, tableId = 50,
		type = "-",
		columns = "sdqa_thresholdId";

	INSERT INTO md_Index
	SET indexId = 118, tableId = 50,
		type = "-",
		columns = "ampExposureId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 51, name = "sdqa_Rating_ForScienceCCDExposure";

	INSERT INTO md_Column
	SET columnId = 538, tableId = 51, name = "sdqa_ratingId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 539, tableId = 51, name = "sdqa_metricId",
		type = "SMALLINT",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Column
	SET columnId = 540, tableId = 51, name = "sdqa_thresholdId",
		type = "SMALLINT",
		notNull = 1,
		displayOrder = 3;

	INSERT INTO md_Column
	SET columnId = 541, tableId = 51, name = "ccdExposureId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 4;

	INSERT INTO md_Column
	SET columnId = 542, tableId = 51, name = "metricValue",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 5;

	INSERT INTO md_Column
	SET columnId = 543, tableId = 51, name = "metricErr",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 6;

	INSERT INTO md_Index
	SET indexId = 119, tableId = 51,
		type = "PRIMARY KEY",
		columns = "sdqa_ratingId";

	INSERT INTO md_Index
	SET indexId = 120, tableId = 51,
		type = "UNIQUE",
		columns = "sdqa_metricId, ccdExposureId";

	INSERT INTO md_Index
	SET indexId = 121, tableId = 51,
		type = "-",
		columns = "sdqa_metricId";

	INSERT INTO md_Index
	SET indexId = 122, tableId = 51,
		type = "-",
		columns = "sdqa_thresholdId";

	INSERT INTO md_Index
	SET indexId = 123, tableId = 51,
		type = "-",
		columns = "ccdExposureId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 52, name = "sdqa_Rating_ForScienceFPAExposure";

	INSERT INTO md_Column
	SET columnId = 544, tableId = 52, name = "sdqa_ratingId",
		type = "BIGINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 545, tableId = 52, name = "sdqa_metricId",
		type = "SMALLINT",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Column
	SET columnId = 546, tableId = 52, name = "sdqa_thresholdId",
		type = "SMALLINT",
		notNull = 1,
		displayOrder = 3;

	INSERT INTO md_Column
	SET columnId = 547, tableId = 52, name = "exposureId",
		type = "INTEGER",
		notNull = 1,
		displayOrder = 4;

	INSERT INTO md_Column
	SET columnId = 548, tableId = 52, name = "metricValue",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 5;

	INSERT INTO md_Column
	SET columnId = 549, tableId = 52, name = "metricErr",
		type = "DOUBLE",
		notNull = 1,
		displayOrder = 6;

	INSERT INTO md_Index
	SET indexId = 124, tableId = 52,
		type = "PRIMARY KEY",
		columns = "sdqa_ratingId";

	INSERT INTO md_Index
	SET indexId = 125, tableId = 52,
		type = "UNIQUE",
		columns = "sdqa_metricId, exposureId";

	INSERT INTO md_Index
	SET indexId = 126, tableId = 52,
		type = "-",
		columns = "exposureId";

	INSERT INTO md_Index
	SET indexId = 127, tableId = 52,
		type = "-",
		columns = "sdqa_metricId";

	INSERT INTO md_Index
	SET indexId = 128, tableId = 52,
		type = "-",
		columns = "sdqa_thresholdId";

-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 

INSERT INTO md_Table
SET tableId = 53, name = "sdqa_Threshold";

	INSERT INTO md_Column
	SET columnId = 550, tableId = 53, name = "sdqa_thresholdId",
		type = "SMALLINT",
		notNull = 1,
		displayOrder = 1;

	INSERT INTO md_Column
	SET columnId = 551, tableId = 53, name = "sdqa_metricId",
		type = "SMALLINT",
		notNull = 1,
		displayOrder = 2;

	INSERT INTO md_Column
	SET columnId = 552, tableId = 53, name = "upperThreshold",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 3;

	INSERT INTO md_Column
	SET columnId = 553, tableId = 53, name = "lowerThreshold",
		type = "DOUBLE",
		notNull = 0,
		displayOrder = 4;

	INSERT INTO md_Column
	SET columnId = 554, tableId = 53, name = "createdDate",
		type = "TIMESTAMP",
		notNull = 1,
		defaultValue = "CURRENT_TIMESTAMP",
		displayOrder = 5;

	INSERT INTO md_Index
	SET indexId = 129, tableId = 53,
		type = "PRIMARY KEY",
		columns = "sdqa_thresholdId";

	INSERT INTO md_Index
	SET indexId = 130, tableId = 53,
		type = "UNIQUE",
		columns = "sdqa_metricId";

	INSERT INTO md_Index
	SET indexId = 131, tableId = 53,
		type = "-",
		columns = "sdqa_metricId";

